# Site settings 配置站点
title: 'Tom-cat'
description: 'IT小白，编程菜鸟，做一个低调，成熟的hacker'
keywords: 'Tom-cat'
url: 'https://fxck12138.github.io' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于博主: '/about.html'
  友情链接: '/friendLink.html'

# 博主
author: true
name: 'Tom-cat'
NickName: 'Fxck'
webtitle: 'Hacker'
bio: 'What fuck'
about: true
aboutyou: '生命不息，折腾不止'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:abc@gmail.com'
  weixin: '' # 你的微信二维码存放的地址
  qq: '' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: 'https://github.com/Fxck1024'
  Codepen: ''
  weibo: ''
  instagram: ''
  Twitter: ''
  Dribbble: ''
  Facebook: ''
  Google: ''
  zhihu: ''
  juejin: ''
  twitch: ''

# 分页
paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2018

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'friendly'

# 友情链接
friends:
  Fxck: 'https://fxck1024.github.io'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: false
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: true
Gitment_owner: 'fxck12138'  # github用户名
Gitment_repo: 'fxck12138.github.io'  # github博客存放的仓库名
client_id: 'd6a4550da61c25f9a416'  # 注册 OAuth Application 后获得的 client_id
client_secret: '19091fae42aa47649fa008bdeed3eabaf47f102a'  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
